### ISSUE TITLE
API suggestion: Move `Error` to crate root

### ISSUE THREAD

**Issue by marcospb19** [bczhc/bzip3-rs#2]
Taking [`serde_json`](https://docs.rs/serde_json) as an example, it seems good to have `Error` and `Result` at the root of your crate so users can refer to it as `bzip3::Error` and `bzip3::Result`.

They can be a link to `bzip3::error::*`, but I don't think it's strictly necessary to have the explicit module exposed in your API.

**Comment by bczhc** [comment]
OK I've made the changes as you suggested. In my old experience also a number of crates are using `crate::errors::{Error, Result}` scheme and not exposing them, just like mine. That's right because moving them to crate root can be more practical and easy-to-use.
